Blog/urls.py
from django.urls import path, include
from .views import BlogView, BlogDetailView

urlpatterns = [
    path("blog/", BlogView.as_view(), name="blog"),
    path("blog_detail/<slug:slug>", BlogDetailView.as_view(), name="blog_detail"),
    path("api/", include("Blog.api.urls")),
]

Order/api/urls.py
from django.urls import path, include
from .views import (WishlistsApiView, WishlistApiView,BasketsApiView, BasketApiView,
                    BasketItemsApiView, RetriveUpdateDeleteBasketItemApiView)

urlpatterns = [
    path("wishlists/", WishlistsApiView.as_view(), name="wishlists_api"),
    path("wishlists/<int:pk>", WishlistApiView.as_view(), name="wishlist_api"),
    path("baskets/", BasketsApiView.as_view(), name="baskets_api"),
    path("baskets/<int:pk>", BasketApiView.as_view(), name="basket_api"),
    path("basket_items/", BasketItemsApiView.as_view(), name="basket_items_api"),
    path("basket_items/<int:pk>", RetriveUpdateDeleteBasketItemApiView.as_view(), name="basket_item_api"),
]

Order/urls.py
from django.urls import path, include
from .views import shopping_cart, wishlist, CheckoutView

urlpatterns = [
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("shopping_cart/", shopping_cart, name="shopping_cart"),
    path("wishlist/", wishlist, name="wishlist"),
    path("api/", include("Order.api.urls")),
]

SuperB/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path("admin/", admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("Blog.urls")),
    path("", include("Core.urls")),
    path("", include("Order.urls")),
    path("", include("User.urls")),
    path("", include("Product.urls")),
)

Order/models.py
from django.db import models
from django.db.models import Sum 
from django.contrib.auth import get_user_model
from Product.models import ProductVersion, Size

User = get_user_model()


class Basket(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="basket")
    is_active = models.BooleanField(default=True)
    total_price = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s basket {self.id}"

    def like_save(self, *args, **kwargs):
        if self.id and self.items is not None:
            self.total_price = self.items.aggregate(total_price = Sum('subtotal'))['total_price']
            return super().save()


class BasketItem(models.Model):

    basket = models.ForeignKey(
        Basket, on_delete=models.CASCADE, related_name="items", null=True, blank=True
    )
    version = models.ForeignKey(
        ProductVersion, on_delete=models.CASCADE, related_name="items"
    )
    count = models.PositiveIntegerField(default=1)
    size = models.ForeignKey(Size, null=True, blank=True, on_delete=models.CASCADE)
    subtotal = models.DecimalField(
        max_digits=7, decimal_places=2, blank=True, null=True, default = 0
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.basket.user.username}'s basket item {self.version.id} {self.id}"

    def save(self, *args, **kwargs):
        if not self.size:
            self.size = self.version.details.first().size
        
        self.subtotal = self.count * self.version.sell_price
        super().save()
        self.basket.like_save()
        print(self.size)
        
        return self

class Wishlist(models.Model):

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="wishlist", null=True, blank=True
    )
    version = models.ForeignKey(
        ProductVersion, on_delete=models.CASCADE, related_name="wishlist"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):

        return f"{self.user.username}'s wishlit  {self.id}"

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from redis import Redis


class User(AbstractUser):

    email = models.EmailField(_("email address"), unique=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    image = models.ImageField(
        upload_to="images/avatars", default="default/admin-photo.jpg"
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['username', ]


class ContactInformation(models.Model):

    COUNTRY_FIRST = "Az"
    COUNTRY_CHOICES = [
        (COUNTRY_FIRST, "Azerbaijan"),
        ("2", "Turkey"),
        ("3", "Germany"),
        ("4", "USA"),
    ]

    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    phone = models.CharField(max_length=16)
    address1 = models.CharField(max_length=64)
    address2 = models.CharField(max_length=64, null=True, blank=True)
    country = models.CharField(
        max_length=16, choices=COUNTRY_CHOICES, default=COUNTRY_FIRST
    )  # api is must
    city = models.CharField(max_length=64)  # api is must
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="contact_info",
        null=True,
        blank=True,
    )
    postal_code = models.CharField(max_length=8, null=True, blank=True)
    default_billing_address = models.BooleanField(default=True)
    default_shipping_address = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):

        return f"{self.first_name}' contact information "


class SubsciriberEmail(models.Model):

    email = models.EmailField(max_length = 64, unique = True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email
    
    def save(self, *args, **kwargs):
        super(SubsciriberEmail, self).save(*args, **kwargs)
        r = Redis(host = '127.0.0.1', port = 6379)
        r.publish('email_channel', self.email)

Order/api/views.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from Order.models import Basket, BasketItem, Wishlist
from .serializers import (
    WishListSerializer,
    BasketItemSerializer,
    BasketSerializer,
    WishListPostSerializer,
    BasketItemPostSerializer,
)
from rest_framework.permissions import (
    IsAuthenticated,
    IsAuthenticatedOrReadOnly 
    )


class GenericApiSerializerMixin:

    def get_serializer_class(self):
        return self.serializer_classes[self.request.method]


class WishlistsApiView(GenericApiSerializerMixin, ListCreateAPIView):

    serializer_classes = {"GET": WishListSerializer, "POST": WishListPostSerializer}

    def get_queryset(self):
        queryset = Wishlist.objects.filter(user = self.request.user)
        return queryset


class WishlistApiView(GenericApiSerializerMixin, RetrieveUpdateDestroyAPIView):

    serializer_classes = {
        "DELETE": WishListPostSerializer, 
        "PATCH": WishListPostSerializer,
        "PUT": WishListPostSerializer,
        }

    def get_queryset(self):
        queryset = Wishlist.objects.filter(user = self.request.user)
        return queryset


class BasketsApiView(ListCreateAPIView):

    queryset = Basket.objects.all()
    serializer_class = BasketSerializer


class BasketApiView(RetrieveUpdateDestroyAPIView):

    queryset = Basket.objects.all()
    serializer_class = BasketSerializer


class BasketItemsApiView(GenericApiSerializerMixin, ListCreateAPIView):

    serializer_classes = {
        "GET": BasketItemSerializer,
        "POST": BasketItemPostSerializer,
    }    
    permission_classes = [IsAuthenticated]


    def get_queryset(self):
        if self.request.user.is_anonymous:
            queryset = BasketItem.objects.all()
        else:
            queryset = BasketItem.objects.filter(basket__user=self.request.user, basket__is_active=True)
        return queryset


class RetriveUpdateDeleteBasketItemApiView(GenericApiSerializerMixin, RetrieveUpdateDestroyAPIView):

    serializer_classes = {
        "GET": BasketItemSerializer,
        "PATCH": BasketItemPostSerializer,
        "PUT": BasketItemPostSerializer,
        "DELETE": BasketItemPostSerializer,
    }

    def get_queryset(self):
        if self.request.user.is_anonymous:
            queryset = BasketItem.objects.all()
        else:
            queryset = BasketItem.objects.filter(basket__user=self.request.user)
        return queryset

Order/views.py
from django.shortcuts import render
from django.views.decorators.cache import never_cache

from django.views.generic import ListView
from User.models import ContactInformation


class CheckoutView(ListView):

    template_name = 'checkout.html'
    model = ContactInformation   
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['billing_address'] = ContactInformation.objects.filter(user = self.request.user, default_billing_address = True).first()
        context['shipping_address'] = ContactInformation.objects.filter(user = self.request.user, default_shipping_address = True).first()
        return context

    
def checkout(request):
    return render(request, "checkout.html")

@never_cache
def shopping_cart(request):
    return render(request, "shopping_cart.html")


def wishlist(request):
    return render(request, "wishlist.html")

Order/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Superb, premium HTML5 &amp; CSS3 template</title>
{% endblock %}


{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/internal.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}" media="all">
{% endblock %}


<body class="onestepcheckout-index-index inner-page">
  <div id="page">


    {% block content %}
    <!-- Main Container -->
    <section class="main-container col2-right-layout bounceInUp animated">
      <div class="main container">
        <div class="row">
          <div class="col-main col-sm-9">
            <div class="page-title">
              <h1>Checkout</h1>
            </div>
            <ol class="one-page-checkout" id="checkoutSteps">
              <li id="opc-billing" class="section allow active">
                <div class="step-title"> <span class="number">1</span>
                  <h3>Checkout Method</h3>
                </div>
                <div id="checkout-step-billing" class="step a-item">
                  <form id="co-billing-form">
                    <fieldset class="group-select">
                      <ul>
                        <li>
                          <label for="billing-address-select">Select a billing and shipping address.</label>
                          <br>
                          <select name="" id="billing-address-select" class="address-select" title="" onChange="">
                            <option value="1" selected="selected">{{ billing_address.first_name }}
                              {{ billing_address.last_name }}
                              {{ billing_address.address1 }}
                              {{ billing_address.get_country_display }}
                            </option>
                          </select>
                        </li>
                        <br>
                      </ul>
                      <a href="{% url 'shopping_cart' %}"><button type="button" class="button"><span>Check
                            Shopping cart</span></button></a>
                      <br> <br>
                      <button id="continue-checkout" type="button" class="button continue"><span>Continue
                            checkout</span></button>
                    </fieldset>
                  </form>
                  <br>
                  <!-- Set up a container element for the button -->
                  <div id="paypal-button-container" style="display: none;"></div>

                  <!-- Include the PayPal JavaScript SDK -->
                  <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD&disable-funding=credit"></script>
                  <script>
                      let continueCheckout = document.getElementById('continue-checkout')
                      let payment = document.getElementById('paypal-button-container')
                          continueCheckout.addEventListener('click', function(){
                            continueCheckout.style.display = 'none'
                            payment.style.display = 'block'
                          })
                  </script>

                  <script>
                    // Render the PayPal button into #paypal-button-container
                    paypal.Buttons({

                      // Call your server to set up the transaction
                      createOrder: function (data, actions) {
                        return fetch('/demo/checkout/api/paypal/order/create/', {
                          method: 'post'
                        }).then(function (res) {
                          return res.json();
                        }).then(function (orderData) {
                          return orderData.id;
                        });
                      },

                      // Call your server to finalize the transaction
                      onApprove: function (data, actions) {
                        return fetch('/demo/checkout/api/paypal/order/' + data.orderID + '/capture/', {
                          method: 'post'
                        }).then(function (res) {
                          return res.json();
                        }).then(function (orderData) {
                          // Three cases to handle:
                          //   (1) Recoverable INSTRUMENT_DECLINED -> call actions.restart()
                          //   (2) Other non-recoverable errors -> Show a failure message
                          //   (3) Successful transaction -> Show confirmation or thank you

                          // This example reads a v2/checkout/orders capture response, propagated from the server
                          // You could use a different API or structure for your 'orderData'
                          var errorDetail = Array.isArray(orderData.details) && orderData.details[0];

                          if (errorDetail && errorDetail.issue === 'INSTRUMENT_DECLINED') {
                            return actions.restart(); // Recoverable state, per:
                            // https://developer.paypal.com/docs/checkout/integration-features/funding-failure/
                          }

                          if (errorDetail) {
                            var msg = 'Sorry, your transaction could not be processed.';
                            if (errorDetail.description) msg += '\n\n' + errorDetail.description;
                            if (orderData.debug_id) msg += ' (' + orderData.debug_id + ')';
                            return alert(msg); // Show a failure message (try to avoid alerts in production environments)
                          }

                          // Successful capture! For demo purposes:
                          console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                          var transaction = orderData.purchase_units[0].payments.captures[0];
                          alert('Transaction ' + transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                          // Replace the above to show a success message within this page, e.g.
                          // const element = document.getElementById('paypal-button-container');
                          // element.innerHTML = '';
                          // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                          // Or go to another URL:  actions.redirect('thank_you.html');
                        });
                      }

                    }).render('#paypal-button-container');
                  </script>
                </div>
              </li>
            </ol>
          </div>
          <aside class="col-right sidebar col-sm-3">
            <div class="block block-progress">
              <div class="block-title ">Your Checkout</div>
              <div class="block-content">
                <dl>
                  <dt class="complete"> Billing Address </dt>
                  <dd class="complete">
                    <address>
                      {{ billing_address.first_name }}<br>
                      {{ billing_address.last_name }}<br>
                      {{ billing_address.phone }}<br>
                      {{ billing_address.address1 }}<br>
                      {{ billing_address.address2 }}<br>
                      {{ billing_address.get_country_display }}<br>
                      {{ billing_address.city }}<br>
                      {{ billing_address.phone }}<br>
                    </address>
                  </dd>
                  <dt class="complete"> Shipping Address <span class="separator"></dt>
                  <dd class="complete">
                    <address>
                      {{ shipping_address.first_name }}<br>
                      {{ shipping_address.last_name }}<br>
                      {{ shipping_address.phone }}<br>
                      {{ shipping_address.address1 }}<br>
                      {{ shipping_address.address2 }}<br>
                      {{ shipping_address.get_country_display }}<br>
                      {{ shipping_address.city }}<br>
                      {{ shipping_address.phone }}<br>
                    </address>
                  </dd>
                  <dd class="complete"> Flat Rate - Fixed <br>
                    <span class="price">$49.00</span>
                  </dd>
                </dl>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </section>
    <!-- Main Container End -->
    {% endblock %}

  </div>
  {% block footer %}

  {% endblock %}
  {% block js %}
  <script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/cloud-zoom.js' %}"></script>
  {% endblock %}
</body>

</html>

Order/templates/shopping_cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  <title>Superb, premium HTML5 &amp; CSS3 template</title>
{% endblock %}


{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/internal.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}" media="all">
{% endblock %}


<body class="inner-page">
<div id="page"> 
  
  
  
{% block content %}
  <!-- Main Container -->
  <section class="main-container col1-layout">
    <div class="main container">
      <div class="col-main">
        <div class="cart">
          <div class="page-title">
            <h1>Shopping Cart</h1>
          </div>
          <div class="table-responsive">
            <form method="post" action="#">
              <fieldset>
                <table class="data-table cart-table" id="shopping-cart-table">
                  <thead>
                    <tr class="first last">
                      <th rowspan="1">&nbsp;</th>
                      <th rowspan="1"><span class="nobr">Product Name</span></th>
                      <th rowspan="1" class="hidden-phone"></th>
                      <th colspan="1" class="a-center"><span class="nobr">Unit Price</span></th>
                      <th class="a-center " rowspan="1">Qty</th>
                      <th colspan="1" class="a-center">Subtotal</th>
                      <th class="a-center" rowspan="1">&nbsp;</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr class="first last">
                      <td class="a-right last" colspan="50"><a href="{% url 'product_list' %}"><button onclick="" class="button btn-continue" title="Continue Shopping" type="button"><span>Continue Shopping</span></button></a>
                        {% csrf_token %}
                        <button class="button btn-update" title="Update Cart" value="update_qty" name="update_cart_action" id="update-cart" type="button"><span>Update Cart</span></button>
                        {% csrf_token %}
                        <button id="empty_cart_button" class="button" title="Clear Cart" value="{{ basket_items.first.basket.id }}" name="update_cart_action" type="button"><span>Clear Cart</span></button></td>
                    </tr>
                  </tfoot>
                  <tbody id="items-parent">
                    <tr class="first odd">
                    </tr>
                  </tbody>
                </table>
              </fieldset>
            </form>
          </div>
          <!-- BEGIN CART COLLATERALS -->
          <div class="cart-collaterals row">
            <div class="col-sm-4">
              <div class="totals">
                <h3>Shopping Cart Total</h3>
                <div class="inner">
                  <table class="table shopping-cart-table-total" id="shopping-cart-totals-table">
                    <colgroup>
                    <col>
                    <col width="1">
                    </colgroup>
                    <tfoot>
                      <tr>
                        <td colspan="1" class="a-left"><strong>Grand Total</strong></td>
                        <td class="a-right"><strong><span class="price" id="grand-total"></span></strong></td>
                      </tr>
                    </tfoot>
                  </table>
                  <ul class="checkout">
                    <li>
                      <button class="button btn-proceed-checkout" title="Proceed to Checkout" type="button"><a href="{% url 'checkout' %}"><span>Proceed to Checkout</span></a></button>
                    </li>
                    <br>
                    <li><a title="Checkout with Multiple Addresses" href="#">Checkout with Multiple Addresses</a> </li>
                    <br>
                  </ul>
                </div>
              </div>
              <!--inner--> 
              
            </div>
          </div>
          
          <!--cart-collaterals--> 
          
        </div>
      </div>
    </div>
  </section>
{% endblock %}
  
</div>
{% block footer %}
{% endblock %}
<!-- JavaScript --> 

{% block js %}
  <script type="text/javascript" src="{% static 'js/shopping-cart.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/parallax.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/cloud-zoom.js' %}"></script>
{% endblock %}
 
</body>
</html>

Order/templates/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  <title>Superb, premium HTML5 &amp; CSS3 template</title>
{% endblock %}

<!-- CSS Style -->

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/internal.css' %}">
{% endblock %}


<body class="customer-account-index customer-account inner-page">
<div id="page"> 

  {% block content %}
    <!-- Main Container -->
    <section class="main-container col2-right-layout">
      <div class="main container">
        <div class="row">
          <div class="col-main col-sm-9">
            <div class="my-account">
              <div class="page-title">
                <h1>My Wishlist</h1>
              </div>
              <div class="my-wishlist">
                <form method="post" action="#" id="wishlist-view-form">
                  <fieldset>
                    <input type="hidden" value="ROBdJO5tIbODPZHZ" name="">
                    <div class="table-responsive">
                      <table id="wishlist-table" class="clean-table linearize-table data-table">
                        <thead>
                          <tr class="first last">
                            <th class="customer-wishlist-item-image">Item</th>
                            <th class="customer-wishlist-item-price">Price</th>
                            <th class="customer-wishlist-item-cart">Action</th>
                            <th class="customer-wishlist-item-remove">Remove</th>
                          </tr>
                        </thead>
                        <tbody id="wishlist_items_parent">
                          
                        </tbody>
                      </table>
                    </div>
                    <div class="buttons-set buttons-set2">
                      <button class="button btn-share" title="Share Wishlist" name="" type="submit"><span>Share Wishlist</span></button>
                      <button class="button btn-add" id="add-all-to-cart" title="Add All to Cart" type="button"><span>Add All to Cart</span></button>
                    </div>
                  </fieldset>
                </form>
              </div>
            </div>
          </div>
          <!-- <aside class="col-right sidebar col-sm-3">
            <div class="block block-account">
              <div class="block-title">My Account</div>
              <div class="block-content">
                <ul>
                  <li><a href="#">Account Dashboard</a></li>
                  <li><a href="#">Account Information</a></li>
                  <li><a href="#">Address Book</a></li>
                  <li><a href="#">My Orders</a></li>
                  <li><a href="#">Billing Agreements</a></li>
                  <li><a href="#">Recurring Profiles</a></li>
                  <li><a href="#">My Product Reviews</a></li>
                  <li><a href="#">My Tags</a></li>
                  <li class="current"><a href="#">My Wishlist</a></li>
                  <li><a href="#">My Downloadable</a></li>
                  <li class="last"><a href="#">Newsletter Subscriptions</a></li>
                </ul>
              </div>
            </div>
          </aside> -->
        </div>
      </div>
    </section>
    <br>
    <!-- Main Container End --> 
  {% endblock %}
</div>
<!-- JavaScript --> 
{% block js %}
  <script type="text/javascript" src="{% static 'js/wishlist_page.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/parallax.js' %}"></script> 
  <script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script>  
  <script type="text/javascript" src="{% static 'js/cloud-zoom.js' %}"></script>
{% endblock %}

</body>
</html>